### PR TITLE
fix: support webpack multi-compiler

### LINKED ISSUE #117: Array of configurations gives vague validation error
Using Webpack 2 and multi-configurations, I get the following output (shortened) and error:

```
[
  {
    "entry": {
      "client": [
        "/Users/sadaf/git_repo/mup-web/src/client.jsx"
      ]
    },
    "output": {
      "path": "/Users/sadaf/git_repo/mup-web/build/locale/fr-FR",
      "filename": "fr-FR.[name].js",
      "publicPath": "//0.0.0.0:8001/"
    },
    "devtool": "eval",
    "module": {
      "preLoaders": [
        {
          "test": {},
          "loader": "eslint-loader",
          "include": [
            "/Users/sadaf/git_repo/mup-web/src"
          ],
          "exclude": "/Users/sadaf/git_repo/mup-web/src/assets"
        }
      ],
      "loaders": [
        {
          "test": {},
          "include": [
            "/Users/sadaf/git_repo/mup-web/src"
          ],
          "loader": "babel-loader",
          "query": {
            "plugins": [
              [
                "react-transform",
                {
                  "transforms": [
                    {
                      "transform": "react-transform-hmr",
                      "imports": [
                        "react"
                      ],
                      "locals": [
                        "module"
                      ]
                    }
                  ]
                }
              ]
            ]
          }
        },
        {
          "test": {},
          "include": [
            "/Users/sadaf/git_repo/mup-web/src/assets/css"
          ],
          "loader": "style!css"
        },
        {
          "test": {},
          "include": [
            "/Users/sadaf/git_repo/mup-web/src"
          ],
          "loader": "json"
        }
      ]
    },
    "resolve": {
      "extensions": [
        ".js",
        ".jsx"
      ]
    },
    "plugins": [
      {
        "options": {
          "0": "/Users/sadaf/git_repo/mup-web/src/assets/svg/**/*.svg",
          "svg": {
            "xmlns": "http://www.w3.org/2000/svg",
            "style": "position:absolute; width: 0; height: 0"
          },
          "svgoOptions": {},
          "name": "sprite.[hash].svg",
          "prefix": "icon-",
          "template": "/Users/sadaf/git_repo/mup-web/node_modules/webpack-svgstore-plugin/src/templates/layout.pug"
        }
      }
    ]
  },
  ...
]

[1] "value" must be an object
```

Perhaps there is an error in my config (though it builds), but this error does not clearly point to the issue.

### PR DESCRIPTION
**Pull request by sadafie**
when provided with an array of configurations, iterate array and validate each configuration
individually

fixes #117

### CODE REVIEW

File: test/utils/allInvalid.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
-import validate from '../../src/index'
 import chalk from 'chalk'
 import util from 'util'
 
+const validate = require('../../src/index').validate
```
Comment (kentcdodds) [inline test/utils/allInvalid.js]: Shouldn't this be getting `validateRoot`?

File: test/utils/allValid.js [hunk 2]
```diff
@@ -1,7 +1,8 @@
-import validate from '../../src/index'
 import chalk from 'chalk'
 import util from 'util'
 
+const validate = require('../../src/index').validate
```
Comment (kentcdodds) [inline test/utils/allValid.js]: Shouldn't this be getting `validateRoot`?

Also, this can be written as:

```javascript
import {validateRoot} from '../../src'
```

**Comment by kentcdodds** [comment]
This is great! LGTM! Thanks!

File: test/utils/allInvalid.js (hunk 1 above)
Comment (sadafie) [inline test/utils/allInvalid.js]: The way I've structured this is that `validateRoot` supports the array of configurations and is the single entry point for `validate-config.js`, as seen [here](https://github.com/js-dxtools/webpack-validator/pull/119/files#diff-ee0e20c822ec0f4af6bdb5b889841c0fR2).

`validate` is simply used for validating the individual properties of the configs, which is done through this utility methods in `allInvalid.js` and `allValid.js`.

Comment (sadafie) [inline test/utils/allInvalid.js]: But open to other suggestions :-)

Comment (kentcdodds) [inline test/utils/allInvalid.js]: Oh, right, I was mistaken, you're good :)

File: test/utils/allValid.js (hunk 2 above)
Comment (sadafie) [inline test/utils/allValid.js]: pushed fix to use import

**Comment by sadafie** [comment]
Curious what the process/timeline is to get an updated version of the pkg. Would like to use this on my current project!

**Comment by kentcdodds** [comment]
Thanks for your patience @sadafie! Hopefully @jonathanewerner or @bebraw can give this a second review soon. If they don't get to it in a few hours, then I'll go ahead and merge it (at which time it will be automatically released).

**Comment by sadafie** [comment]
Great, take your time with it! It took me a while to submit this PR anyways. I was just curious if I should hold off on using webpack-validator in my project if the overall process takes longer, which it doesn't sound like it does. thanks!

File: src/index.js [hunk 3]
```diff
@@ -59,20 +67,10 @@ const makeSchema = (schemaOptions, schemaExtension) => {
...
-  },
-}
-
-// Easier consumability for require (default use case for non-transpiled webpack configs)
-module.exports = function validate(config, options = {}) {
+function validate(config, options) {
   const {
     // Don't return the config object and throw on error, but just return the validation result
     returnValidation, // bool
-    quiet, // bool
```
Comment (bebraw) [inline src/index.js]: Why to drop this line?

File: src/index.js [hunk 4]
```diff
@@ -92,11 +90,36 @@ module.exports = function validate(config, options = {}) {
     process.exit(1)
   }
 
+  return config
+}
+
+// Easier consumability for require (default use case for non-transpiled webpack configs)
+function validateRoot(config, options = {}) {
+  const {
+    quiet,
```
Comment (bebraw) [inline src/index.js]: Ah, it went here. Nm.

**Comment by bebraw** [comment]
LGTM.

**Comment by bebraw** [comment]
Looks like this broke the API contract.

In `2.2.3` `const validate = require('webpack-validator');` returns a function. `2.2.4` returns an object. That breaks a lot of code. 😢

**Comment by kentcdodds** [comment]
uh oh :-/ Yeah, we should fix that asap

File: src/index.js [hunk 5]
```diff
@@ -92,11 +90,36 @@ module.exports = function validate(config, options = {}) {
...
+
   if (!quiet) {
     console.info(chalk.green('[webpack-validator] Config is valid.'))
   }
 
-  return config
+  return validationResult || multiValidationResults
 }
 
-module.exports.Joi = Joi
```
Comment (bebraw) [inline src/index.js]: This breaks the API. So we need to revert these lines to fix the API compatibility.

**Comment by sadafie** [comment]
hmm, not super clear how that happened. is this because of the multi-exports? also, there should be a test case for this too!

File: src/index.js (hunk 5 above)
Comment (sadafie) [inline src/index.js]: Ok. So my commonjs syntax knoweldge is lacking... how would you do multi-exports if I want to make both `validate` and `validateRoot` available?

Comment (bebraw) [inline src/index.js]: Basically the old implementation did two things:

1. `module.exports = function validate(config, options = {}) {`
2. `module.exports.Joi = Joi`

So it attached `Joi` to the function it exports by default. `exports` returns an object` by definition.

Changing the exports the way they were would fix it. The import at test should change too at least.

Comment (sadafie) [inline src/index.js]: Would like to take a stab at this since it was my code that broke it, but unfortunately I will be away from a computer for the next 8 hours ago. LMK how urgent this is. I could submit a PR tomorrow if that's not too late.

Comment (bebraw) [inline src/index.js]: No worries. I'm just doing a little patch.

Comment (kentcdodds) [inline src/index.js]: Thanks @bebraw. I'm in a meeting right now.

Comment (bebraw) [inline src/index.js]: Ok, PRd. Have a look and merge if that looks good when you have time.

**Comment by kentcdodds** [comment]
This has been fixed. Thanks again for your contribution @sadafie :)

**Comment by sadafie** [comment]
Thanks for the patch @bebraw! Sorry again about the regression.

**Comment by bebraw** [comment]
No worries. A integration test that installs the package and then validates something simple would have caught it (good another PR ;) ).

**Comment by kentcdodds** [comment]
We should look into [`dont-break`](http://npm.im/dont-break)

**Comment by bebraw** [comment]
That looks like a nice way to handle it.

Another option is to write a little [bash script](https://github.com/antwarjs/antwar/blob/921f44f12201c8cba521c65190ea01cf7f90d955/tests/travis.sh) that clones the repo and then runs something against it though `dont-break` is probably the way to go given webpack-validator has actual usage in the wild.
