### PR TITLE
Quiet mode

### LINKED ISSUE #69: Add option not to print on success?
Printing `[webpack-validator] Config is valid.` on success isn't good if you are using webpack's `--json` option with webpack-validator as that leads to broken output.

Do you think it would make sense to add some sort of option to disable printing on success? How would you handle this?

Related: https://github.com/survivejs/webpack/issues/79

### PR DESCRIPTION
**Pull request by bebraw**
I added support for `quiet` mode.

As I had some trouble with `npm link`, it would be good if you could have a look at the cli side. It should work but better to be safe than sure. It also insisted on rewriting the whole bin file (encoding or file ending problem?).

Closes #69.

### CODE REVIEW

**Comment by jonathanewerner** [comment]
@nyrosmith could you check that cli works on this branch? 
I guess that the rewrite could have something to do with newlines on windows vs mac? (@nyrosmith uses windows).

**Comment by nyrosmith** [comment]
I'll check that ASAPpe I get some time today...

File: src/bin/webpack-validator.js [hunk 1]
```diff
@@ -1,61 +1,65 @@
...
+
+function validateConfig(webpackConfigFile, quiet) {
+  if (!quiet) console.log(`Reading: ${webpackConfigFile}`)
+  const config = require(path.join(process.cwd(), webpackConfigFile))
+  const validationResult = validate(config, schema, {
+    returnValidation: true,
+    quiet,
+  })
+  if (validationResult.error) {
+    if (!quiet) console.info(validationResult.error.annotate())
```
Comment (nyrosmith) [inline src/bin/webpack-validator.js]: I don't think it's a good idea to supress Error output

**Comment by nyrosmith** [comment]
Besides the fact that the CLI doesnot print errors everything else looks good to me.

File: src/bin/webpack-validator.js (hunk 1 above)
Comment (bebraw) [inline src/bin/webpack-validator.js]: Good point. I'll change that.

Comment (bebraw) [inline src/bin/webpack-validator.js]: It might be good to output the error through STDERR but that can be done later.

**Comment by nyrosmith** [comment]
LGTM!
@bebraw Can you squash the commits into one? After that I merge it

**Comment by bebraw** [comment]
@nyrosmith Squashed to single commit.

**Comment by nyrosmith** [comment]
Thx @bebraw
